name: Streamlit application CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: 'x64'
        
    - name: Install linux packages
      run: |
        sudo apt-get -qq update && sudo apt-get -qq install -y zip && sudo apt-get -qq install -y unzip
        
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{secrets.AWS_DEFAULT_REGION}}
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Login to Amazon CodeArtifact
      id: login-codeartifact
      env:
        CODEARTIFACT_DOMAIN: ${{ secrets.CODEARTIFACT_DOMAIN }}
        CODEARTIFACT_REPO: ${{ secrets.CODEARTIFACT_REPO }}
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: |
        echo Getting CodeArtifact authorization...
        CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain "${CODEARTIFACT_DOMAIN}" --query authorizationToken --output text)
        PIP_INDEX_URL="https://aws:${CODEARTIFACT_AUTH_TOKEN}@${CODEARTIFACT_DOMAIN}-${AWS_ACCOUNT_ID}.d.codeartifact.${REGION}.amazonaws.com/pypi/${CODEARTIFACT_REPO}/simple/"
        echo "::set-output name=pip-index-url::$PIP_INDEX_URL"
        
    - name: Build, tag, and push the image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.REPO_NAME }}
        PIP_INDEX_URL: ${{ steps.login-codeartifact.outputs.pip-index-url }}
      run: |
        # Build a docker container and push it to ECR 
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY --build-arg PIP_INDEX_URL=$PIP_INDEX_URL .
        echo "Pushing image to ECR..."
        docker push $ECR_REGISTRY/$ECR_REPOSITORY
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY" 
        
    - name: Delete Untagged Images
      env:
       ECR_REPOSITORY: ${{ secrets.REPO_NAME }}
       REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: |
        IMAGES_TO_DELETE=$( aws ecr list-images --region $REGION --repository-name $ECR_REPOSITORY --filter "tagStatus=UNTAGGED" --query 'imageIds[*]' --output json)
        aws ecr batch-delete-image --region $REGION --repository-name $ECR_REPOSITORY --image-ids "$IMAGES_TO_DELETE" || true
      shell: bash
      
    - name: ECS Force Deployment
      env:
        FARGATE_CLUSTER: ${{ secrets.FARGATE_CLUSTER }}
        FARGATE_SERVICE: ${{ secrets.FARGATE_SERVICE }}
      run: |
        aws ecs update-service --cluster $FARGATE_CLUSTER --service $FARGATE_SERVICE --force-new-deployment
        

        
